POST  https://localhost:8443/pedagogia/api/login
Content-Type: application/json

{ "email": "user@na.com.br", "senha": "123"}

###

GET https://localhost:8443/pedagogia/api/usuarios/na@na.com.br
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQG5hLmNvbS5iciIsImV4cCI6MTU0MjU3ODE2NywiUk9MRVMiOiJST0xFX1VTRVIifQ.LsI_Q1suKeVARlC48XJWynRYr3o0BiqAIdIF6keIlQwgqySMXTFfisF1USNBiKL7-chYBpzeFY_YmLFL1OzIQA

###



GET https://localhost:8443/pedagogia/api/usuarios/na@na.com.br
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuYUBuYS5jb20uYnIiLCJleHAiOjE1NDI1NzY2MjgsIlJPTEVTIjoiUk9MRV9BRE1JTiJ9.bpeKIBiN9uSbmIJsY4-f5_klVlJ0bVssv5buaQFh9DCjE8lw5Tyqiwb7gOZ6EQs6XPu4qDdFGjlnCGTTJexh2Q

###

POST https://localhost:8443/pedagogia/api/alunos
Content-Type: application/json

{ "nome": "oto", "sede": {"id": 1}}

###

GET https://localhost:8443/pedagogia/api/alunos

###

GET https://localhost:8443/pedagogia/api/alunos/1

###

POST https://localhost:8443/pedagogia/api/turmas
Content-Type: application/json

{
    "sede": {"id": 1},
    "nome": "bar",
    "professores": [{"id": 1}],
    "alunos": [{"id": 1}, {"id": 2}],
    "diaSemana": "WEDNESDAY"
}

###

GET https://localhost:8443/pedagogia/api/turmas?diaSemana=WEDNESDAY&idSede=1

###

GET https://localhost:8443/pedagogia/api/entregas-tema?idTurma=1&idTema=1

###

POST https://localhost:8443/pedagogia/api/entregas-tema
Content-Type: application/json

{ "turma": {"id": 12}, "aluno": {"id": 3}, "entregue": true, "data": "2012-04-23T18:25:43.511Z" }

###

https://localhost:8443/pedagogia/api/aulas?idTurma=1&idMateria=1&data=2018-11-07T03:00:00.000Z

###

GET https://localhost:8443/pedagogia/api/aulas?idTurma=1&idMateria=1&idProfessor=9&data=

###

POST https://localhost:8443/pedagogia/api/aulas
Content-Type: application/json

{
    "turma": {"id": 1},
    "professor": {"id": 9},
    "materia": {"id": 1},
    "data": "2012-04-23",
    "observacao": "obs",
    "capitulo": {"id": 5},
    "presencas": [
        {"aluno": {"id": 3}, "presente": true},
        {"aluno": {"id": 4}, "presente": true}
    ]
}

