
POST http://localhost:8080/pedagogia/api/alunos

{ "nome": "oto", "sede": "/api/alunos/1" }

###

GET http://localhost:8080/pedagogia/api/alunos

###

GET http://localhost:8080/pedagogia/api/turmas/12