INSERT INTO aluno (nome,matricula,email,sede_id) VALUES
('ADELLE CHRISTINA LEITE REBOUÇAS',15421,'adellechristina@hotmail.com',1),
('ADRIANA BIANQUI',21223,'adriana.bianqui@yahoo.com.br',1),
('ADRIANA HISSA SAMPAIO',22072,'adrianahissas@gmail.com',1),
('ADRIANO ROGÉRIO DE ARAÚJO PINHEIRO',21667,'adriano.rogerio@gmail.com',1),
('ALBERTO TARGINO NETO',12313,'betotargino@yahoo.com.br',1),
('ALESSANDRA MAGALHAES',19590,'lecamag@yahoo.com.br',1),
('ALEXANDRE DE PAULA',23398,'alexpinh@hotmail.com',1),
('ALEXANDRE DO CARMO SABINO DA SILVA',19320,'carmo202009@hotmail.com',1),
('ALEXANDRE SANTIAGO FREIRE',17189,'spacernet@gmail.com',1),
('ALFREDO BEZERRA PINHEIRO NETO',4572,'alfredobpneto@hotmail.com',1),
('ALINE GONÇALVES PINTO',23294,'agopinsemam@gmail.com',1),
('ALINE MOTA ALBUQUERQUE LOUREIRO',2392,'alinemaloureiro@gmail.com',1),
('ANA ALICE DIAS ALBUQUERQE',4620,'analicedias@hotmail.com',1),
('ANA CAROLINA LUCENA PINHEIRO',23598,'',1),
('ANA CAROLINE ARAÚJO LIMA',1345,'acalimac@gmail.com',1),
('ANA CLAUDIA VIANA',20076,'acviana@petrobras.com.br',1),
('ANA CRISTINA CUNHA',22073,'cris78@gmail.com',1),
('ANA LUIZA ALMEIDA DO MONTE',5306,'analuiza.monte@gmail.com',1),
('ANA MARIA LUCENA',20085,'anamarialuce@hotmail.com',1),
('ANA PAULA FONSECA BRAGA',18736,'anapaula_vive@yahoo.com.br',1),
('ANDREA DE CASTRO FIALHO',15963,'vanguarda@estilovanguarda.com.br',1),
('ANDREA FERREIRA DE OLIVEIRA',6634,'andreaferreiraoliveira@gmail.com',1),
('ANDREA PEREIRA DE SOUSA MAGALHÃES',23113,'andreamagalha@gmail.com',1),
('ANDRE PASCOAL RODRIGUES',17190,'pascial.andre@gmail.com',1),
('ANGELA ANGELIM PESSOA GAERTNER',13822,'angelagae@yahoo.com.br',1),
('ANNA KAROLYNA LOIRINO BORGES',22971,'karolynaborges@gmail.com',1),
('ANNE MACHADO DE OLIVEIRA PIAS',19321,'pias_12@yahoo.com.br',1),
('ANTONIO AGEU CARDOSO DE ARAUJO',12792,'aguuga@ymail.com',1),
('ANTONIO ALVES DE MOURA',15048,'0211moura@gmail.com',1),
('ANTONIO CLAUDIO ALVES REGINO',23292,'claudioregino64@gmail.com',1),
('ANTONIO CRUZ CASTRO',22972,'antonio.c.castro@gmail.com',1),
('ANTONIO DE MELO PAIVA',14517,'antoniompaiva@yahoo.com.br',1),
('ANTÔNIO JOSÉ NOBREGA JUNIOR',22618,'',1),
('ANTONIO WALTER FARIAS NETO',11745,'walterfarias27@gmail.com',1),
('ARTHUR SANTOS VIANA DE OLIVERIA',22606,'arthursviana@outlook.com',1),
('AUGUSTO EMMANUEL GOES FERREIRA DI BRUNO',15422,'augustogoes1@gmail.com',1),
('BÁRBARA CECÍLIA AUGUSTO SAMPAIO',21107,'basamorim@hotmail.com',1),
('BRUNA BARDAWIL ROLIM',20507,'brunarolim@hotmail.com',1),
('BRUNA LARISSA NOGUEIRA DE CARVALHO',19523,'bruna.nogueira9@outlook.com',1),
('CAMILA SOARES MARREIROS MARTINS',16331,'',1),
('CARLA EUGENIA FERREIRA DA SILVA',17191,'carlinha_272013@outlook.com',1),
('CARLA NOTTINGHAM BENEVIDES AZEVEDO',22973,'carlanott@gmail.com',1),
('CARMEM LUCIA DANTAS MOURA',16714,'carmemldmoura@gmail.com',1),
('CARMEN TERESINHA PEREIRA FRANCISS',18480,'ctpfranciss@gmail.com',1),
('CELANA MARIA CARNEIRO TAPETY',5569,'celana@oi.com.br',1),
('CÉZAR AUGUSTO DE MORAIS',14312,'cezarlara@ibest.com.br',1),
('CLARISSA CAVALCANTE BARROSO',22075,'clarissa.barroso@sefaz.ce.gov.br',1),
('CRISTIANE CARACAS DE SOUZA CIDADE',16815,'caracascidade@yahoo.com.br',1),
('DANIEL DE SOUZA MONTEIRO',13827,'dsouzamonteiro7@gmail.com',1),
('DANIELLE NASCIMENTO JUCÁ',7841,'dnjuca@yahoo.com.br',1),
('DARIO GABRIEL GOMES AMORIM',19033,'dariogabriel2012@gmail.com',1),
('DELANO GURGEL SILVEIRA',22078,'delanogs@gmail.com',1),
('DENISE BEZERRA MARCELO',19065,'denisemarcelo22@gmail.com',1),
('DENNYS BAETAS ROCHA',20971,'dbaetas@yahoo.com.br',1),
('DIEGO GASPAR DE OLIVEIRA',6610,'diego.gaspar.oliveira@gmail.com',1),
('DIEGO MIRANDA ALCÂNTARA',22974,'diegoalcantara38@gmail.com',1),
('EDNA MARIA BEZERRA SILVA',20711,'ednasilva@agu.gov.br',1),
('ELAINE PIRES DE QUEIROZ',22079,'ellainepires@gmail.com',1),
('ELIANE MARIA DA ROCHA PEREIRA',15200,'hemrp2@hotmail.com',1),
('ELISA DE SOUZA DA SILVA',16879,'chocolatemeioamargo7@outlook.com',1),
('ELIZABETH MARIA MALHEIROS NUNES',9666,'elizabethluzmalheiros@gmail.com',1),
('EMILIANA MARIA COSTA BARROS SAMPAIO',21409,'emilianabarros@uol.com.br',1),
('ENEIDA AMORIM PONTES',21414,'eneida@mundifiat.com.br',1),
('ERICKSON RIBEIRO',5566,'erickson.ribeiro@gmail.com',1),
('ERIVANIO SILVA GONÇALVES',15185,'',1),
('ERLIENEIDE ALVES GONÇALVES',13810,'erlieneide@gmail.com',1),
('ERYKA FLORENICE PINHEIRO BARRETO',22975,'erykabarreto62@gmail.com',1),
('ESTHER RIBEIRO STUDART DA FONSECA',11589,'estherstudart@terra.com.br',1),
('EUGÊNIA FELICIO',22617,'',1),
('FABIANO FREITAS DOS SANTOS',14250,'fafsam@hotmail.com',1),
('FABIANO MELQUIADES',17098,'',1),
('FABIO DE ASSIS LOBO DE SOUSA',18481,'prof.fabio.lobo@gmail.com',1),
('FABIO EDUARDO NUNES',19038,'nunesfabio@hotmail.com',1),
('FELIPE AZEVEDO DE VASCONCELOS',19026,'felipeav146@gmail.com',1),
('FELIPE LOPES FERREIRA',10865,'ffcorretor@gmail.com',1),
('FLAVIA PINHEIRO DE ALENCAR PINTO',4406,'flavia08pp@gmail.com',1),
('FRANCINEIDE PEREIRA MOURA',14508,'moura.francineide@bol.com.br',1),
('FRANCISCA GILSELIA ROCHA PAIVA',14467,'',1),
('FRANCISCO ALEX DIAS ALBUQUERQUE',10870,'alexdial@hotmail.com',1),
('FRANCISCO AYMORÉ BAPTISTA NETO',21108,'aymoreneto@gmail.com',1),
('FRANCISCO DANIEL MESQUITA RODRIGUES CRISPIM',11575,'crispimdaniel10@gmail.com',1),
('FRANCISCO JOSÉ DE LIMA',7110,'frank.fjl@gmail.com',1),
('FRANCISCO ROBERTO DA SILVA GOMES',17467,'',1),
('FRANCISCO RONALDO ARAÚJO LIMA',20969,'',1),
('FRANCYON MAIA DANTAS',23599,'',1),
('GABRIELA CAVALCANTE BARROSO',23432,'',1),
('GABRIEL VIDAL GONDIM',10550,'gabriel-gondim@outlook.com',1),
('GAZZINEU MARCOS CAVALCANTE BRITO',10872,'gaz.marcus@gmail.com',1),
('GEORGIANA SALES LOUREIRO',3423,'gsaleslcardoso@gmail.com',1),
('GERARDO FERNANDES COELHO FILHO',21000,'coelhogerardo@gmail.com',1),
('GILBERTO DA CRUZ BASTOS',13823,'gilbastos.adv@gmail.com',1),
('GILBERTO MOREIRA VERAS JÚNIOR',4871,'dudaveras@hotmail.com',1),
('GIOVANNI SANTOS CARVALHO',22080,'giovanni.santos.carvalho@gmail.com',1),
('GISELE LEAL DE PAULA',17309,'backpackersce@hotmail.com',1),
('GIULIANO SALES LOUREIRO',3160,'giuliano@servis.com.br',1),
('GUGLIELMO MARCONI VENCESLAU',21066,'marconi@oriontelecom.com.br',1),
('HANIEL LOURENCO DUARTE',17836,'haniellcmf@gmail.com',1),
('HAYRLES DA CONCEIÇÃO FREITAS DE MORAES ALCÂNTARA',21444,'hayrles_freitas@hotmail.com',1),
('HELENA LUCIA DE BRITO SIEBRA E OLIVEIRA',1011,'helena_siebra@yahoo.com.br',1),
('HELOISA CLARA DE ALMEIDA PATRIOTA LOBO',18482,'heloisaclara20@gmail.com',1),
('HENRIQUE AUGUSTO PEREIRA PONTES',21467,'augustopontes@mundifiat.com.br',1),
('HERBERT PEREIRA TORRES CAVALCANTE',9618,'herberttorres84@icloud.com',1),
('HÉRICA MARIA DE LIMA',11279,'herica_lima1@hotmail.com',1),
('HERMANO JOSÉ LUCENA PONCIANO',6479,'hermano.jose@yahoo.com.br',1),
('HISNIA LARISSA SILVA DE ARAGÃO',15052,'hisnia@gmail.com',1),
('HONORINA MARIA DE ROSALMEIDA',22977,'noralmeida287@gmail.com',1),
('IANNE BENÍCIO BRAGA',15163,'iannebbraga@hotmail.com',1),
('ICARO SILVA LOIOLA COSTA',16193,'icarodfaffa@gmail.com',1),
('IGOR ALEXANDRE ALENCAR DE AGUIAR',23293,'igoralencardeaguiar@gmail.com',1),
('INÊS SILVIA CARNEIRO BARBOSA',10866,'inescb013@gmail.com',1),
('ISABEL LUARA DE ARAÚJO CUNHA',16586,'luaraisabel@hotmail.com',1),
('IVALÔNY MACIEL MANGUEIRA',21098,'ivalony.advogado@gmail.com',1),
('IVNA DE SOUSA',23114,'ivna_ursino@yahoo.com.br',1),
('IZABELLA MUSA PAZ MARINHO GIRÃO',20767,'izabellagirao@hotmail.com',1),
('JACKELYNN PESSOA LIMA',23296,'jackelynnlima@gmail.com',1),
('JAIANA LOPES DE ARAÚJO',20906,'jaiana.lopes@hotmail.com',1),
('JANE MARY DE MIRANDA LIMA MARTINS',11542,'janemirandamar@gmail.com',1),
('JAQUELINE ASSUNCAO DE LIMA BRAGA',19891,'jaquelineassuncao7@hotmail.com',1),
('JEOVAM LEMOS CAVALCANTE',20136,'jeovamlemos@hotmail.com',1),
('JOANA MARIA SOUTO LOPES',11554,'joanamsl@hotmail.com',1),
('JOÃO BASTOS FREIRE NETO',10888,'joaobastosgeriatra@gmail.com',1),
('JOÃO BATISTA VIDAL',14462,'jbvidal7@gmail.com',1),
('JOÃO HENRIQUE GONÇALVES',21855,'jhgon70@gmail.com',1),
('JOAO RAMOS DA SILVA NETO',18276,'joaonetoo@gmail.com',1),
('JOAQUIM MAGALHÃES BEZERRA FILHO',23397,'joaquimfilho@hotmail.com',1),
('JOSÉ AGUIAR DE OLIVEIRA',10362,'aguiar.joliv@gmail.com',1),
('JOSÉ ARAGÃO E ALBUQUERQUE NETO',21016,'aragao@magis.com.br',1),
('JOSE DANIEL BRANDAO DE OLIVEIRA',22611,'zedaniel.med@gmail.com',1),
('JOSE EDIARLEY FARIAS DE CARVALHO',19029,'ediarley87@gmail.com',1),
('JOSEFA ABIGAIL CRUZ E SILVA',11241,'cruznabol@yahoo.com.br',1),
('JOSÉ OSVALDO PONTES NETO',21227,'opneto@gmail.com',1),
('JUBYA LIMA RODRIGUES BASTOS',17192,'jubya@terra.com.br',1),
('JULIANA DANTAS LUSTOSA',22979,'lustosa.ju@gmail.com',1),
('JULIANA ROLIM',23399,'',1),
('JULIO CESAR SOUZA FERREIRA',13813,'jcs.nib@gmail.com',1),
('KALID NOGUEIRA CHOUDHURY',7125,'kalidnc@gmail.com',1),
('KALINA ALENCAR CUNHA FEITOSA',15966,'kalina.feitosa2015@gmail.com',1),
('KALYNE MADEIRA FURTADO',16044,'kalynemf@ig.com.br',1),
('KELLY CABRAL',5565,'kellycabral13@gmail.com',1),
('KELLY FERREIRA MARQUES BOTELHO AGUIAR',261,'kellyfmba@gmail.com',1),
('LARISSA CARVALHO CÂMARA',21435,'larissaccamara@gmail.com',1),
('LAURA TEREZINHA DA SILVA',22649,'',1),
('LAURENCE VIGUIER',19591,'lolo.viguier.29@gmail.com',1),
('LEANDRO BOTELHO AGUIAR',128,'lbotelhoaguiar@gmail.com',1),
('LEANDRO COSTA CHAVES',11254,'lecoast@gmail.com',1),
('LEILA DE OLIVEIRA LOBÃO',22614,'lobaole@gmail.com',1),
('LEOCADIA DEMBOGURSKI',22616,'lcd174@hotmail.com',1),
('LEVI BAYDE RIBEIRO',3040,'levibayde@gmail.com',1),
('LIA SOARES DANTAS',11590,'liadantas1@yahoo.com.br',1),
('LILIANE MARIA MONTEIRO DE ARAÚJO PEREIRA',4116,'lilianempereira@gmail.com',1),
('LIVIANE DE MENESES VASCONCELOS',17685,'livianemeneses@hotmail.com',1),
('LUCELENA PETRONILIO AGUIAR',3262,'lena.aguiar@hotmail.com',1),
('LUCIANA DE ANDRADE NORÕES',4233,'lnoroes@hotmail.com',1),
('LUCIANA FAÇANHA TORRES',8874,'rbvendas.luciana@hotmail.com',1),
('LUCIANA MARIA VIANA SALES',16816,'lucianamariavs@hotmail.com',1),
('LUCIANE PONTE DE MELO',19028,'luciane_ponte@yahoo.com.br',1),
('LUCIANO BRAGA LIBORIO',17413,'lucianobraga@rejuntamix.com.br',1),
('LUCIANO RODRIGO STUHLER DO NASCIMENTO',7334,'nascimen@uol.com.br',1),
('LUCIENE BOSCO DE OLIVEIRA',21441,'',1),
('LUCIENE FÉLIX DE SOUSA',11746,'lucienefs2011@hotmail.com',1),
('LUCIENE MENDES LACERDA',20080,'',1),
('LUÍS SÉRGIO SANTOS JUNIOR',12848,'lss_jotaerre@hotmail.com',1),
('LUIZ ANTONIO SIMONETTI GOMES',10889,'luiz-simonetti@ibest.com.br',1),
('LUIZ CARLOS CABRAL',1075,'domcabral120@hotmail.com',1),
('LUZIA LOBO MOREIRA',13223,'luzlomoreira@hotmail.com',1),
('MANUEL TAVARES FILHO',14511,'manuel.filho@servis.com.br',1),
('MARA NUCIA SILVEIRA VITALINO',8269,'maranucia@gmail.com',1),
('MARCIA FERNANDA MORENO',22301,'fernanda.moreno@hotmail.com',1),
('MARCIA REGINA DE ARAUJO VALE',9036,'marcia@arxweb.com.br',1),
('MARCIO AZEVEDO SILVA',17688,'magomarcio1@hotmail.com',1),
('MARCO ANTONIO MENA',19745,'menasp@hotmail.com',1),
('MARCOS ANTONIO LACERDA PEREIRA',16523,'marcosalpereira@gmail.com',1),
('MARCOS KLEIN ANTUNES',19735,'mklein@oriontelecom.com.br',1),
('MARCUS ANTONIO TEIXEIRA',6443,'marcimo65@hotmail.com',1),
('MARCUS CARVALHO DE MATOS',979,'mcmnac@gmail.com',1),
('MARIA ANGELA SILVA LIMA',7806,'angelaslima@gmail.com',1),
('MARIA APARECIDA FRANCISCA DE SOUZA',14260,'maria.coach@yahoo.com.br',1),
('MARIA APARECIDA XAVIER BRAGA',5314,'cidaxbraga@gmail.com',1),
('MARIA CELESTINA SABINO DE OLIVEIRA',16777,'celeoliveira6@gmail.com',1),
('MARIA DE JESUS PIRES DE SOUZA',17601,'mjassessoria2011@hotmail.com',1),
('MARIA DO CARMO NOGUEIRA RIBEIRO',12791,'mdcnr@yahoo.com.br',1),
('MARIA DO SOCORRO MACAMBIRA MARQUES',4581,'socorrom@fortalnet.com.br',1),
('MARIA ELISENE PINTO',18416,'marelisene@yahoo.com.br',1),
('MARIA GOMES VENÂNCIO',2403,'mariavenancio@gmail.com',1),
('MARIA GORETI CAVALCANTE BARROSO',23290,'gorettibarroso@yahoo.com.br',1),
('MARIA GORÉTT FRANKLIN MARACABA',13550,'marigorefm@hotmail.com',1),
('MARIA ILMACIR SIQUEIRA MACHADO',16771,'ilmacir@yahoo.com.br',1),
('MARIA IVONEIDE DA SILVA',7327,'neidepmf@gmail.com',1),
('MARIA IZABEL FARIAS DOS SANTOS',18441,'',1),
('MARIA JOSÉ DE ARAÚJO COSTA',22647,'',1),
('MARIANA MACEDO MOURA',5305,'marimmoura@gmail.com',1),
('MARIANA RUTH LEÔNCIO DA PONTE',1226,'marianaruthlp@hotmail.com',1),
('MARIA NORBERTA VIANA',18544,'mnorbertaviana@hotmail.com',1),
('MARINA ROCHA ROLIM',17412,'marinarocharolim@hotmail.com',1),
('MÁRIO AMÉRICO VIANA DE OLIVEIRA',19737,'mario.americovo@gmail.com',1),
('MARLA SELANA PONTES MOTA',21228,'marlasolara@gmail.com',1),
('MARYLEE BRITO GOMES PINTO',6242,'maryleebritto@gmail.com',1),
('MATEUS DE SOUZA DA SILVA',16877,'mateusdesouza3110@hotmail.com',1),
('MAXWEL RODRIGUES FERREIRA',22610,'maxwelrf@hotmail.com',1),
('MAYSA NOBRE NOGUEIRA',11576,'maysanobre@gmail.com',1),
('MICHELE MAIA CIPRIANO',23115,'',1),
('MICHEL PINHO DE ALCÂNTARA',16520,'michelp.alcantara@yahoo.com.br',1),
('MILA MARACABA MOREIRA',13551,'mila.maracabamoreira@gmail.com',1),
('MILENA AGUIAR FERREIRA GOMES PEREIRA',18487,'milenaafgp@hotmail.com',1),
('MURIEL BRUNELLO',18279,'muriel.brunello@gmail.com',1),
('NANCY ABUD ABIFADEL BARROZO',1231,'nancyabifadel@hotmail.com',1),
('NELLY JEREISSATI BARBOSA TEIXEIRA',23613,'',1),
('NEUZA MARCIA FALCAO LOPES',978,'neuzamarcia@yahoo.com',1),
('ORLANDO DE JESUS SILVA FILHO',22619,'',1),
('OSMAR DIÓGENES PARENTE',3984,'osmardiogenes@terra.com.br',1),
('PATRICIA DALE COUTO',21413,'patriciadale@hotmail.com',1),
('PATRICIA DIAS',6943,'ps_dias@hotmail.com',1),
('PATRICIA GOMES PEIXOTO SEIXAS',22981,'arq_patriciagomes@hotmail.com',1),
('PAULA THALITA LIMA SANTOS',19044,'thalitauece@gmail.com',1),
('PAULO PINTO DE MOURA JÚNIOR',670,'paulo.moura.junior@gmail.com',1),
('PAULO RICARDO FERREIRA VIANA',23295,'ricardovianaapv@gmail.com',1),
('PRISCYLLA MESQUITA GOMES',17097,'',1),
('RACHEL BOTELHO DE QUEIROZ',15414,'rachebq@hotmail.com',1),
('RAFAEL LIMA MONTENEGRO',672,'professormontenegro@gmail.com',1),
('RAFHAEL FERNANDES PEREIRA',19076,'pereiraufv@yahoo.com.br',1),
('RAISSA DE OLIVEIRA SOARES',20073,'oliveirasoraiss@gmail.com',1),
('RAQUEL PESSOA DE CARVALHO',14976,'raquelpessoa@hotmail.com',1),
('RAQUEL PINHEIRO SÁ MATOS',17774,'raquel_sa@hotmail.com',1),
('RAUL FIGUEIRA MIRANDA',22608,'raulfmiranda@gmail.com',1),
('REGINA DE FATIMA RIBEIRO LIMA',18518,'rlimasm@hotmail.com',1),
('REGINA LÚCIA BARROS LEAL DA SILVA',21014,'rgnbarrosleal@gmail.com',1),
('REGIS COE GIRAO',19070,'recgirao@yahoo.com.br',1),
('RENATA VENÂNCIO MOTA',7827,'renatavenanciomota@gmail.com',1),
('RENATO WALTER ROLIM RIBEIRO',23600,'',1),
('RICARDO SÉRGIO CAVALCANTE GONDIM',3721,'ricardosergio@servis.com.br',1),
('RICARDO WILLIAM GASPAR',22088,'ricardowilan@gmail.com',1),
('ROBÉRIO GUIMARÃES FREIRE',22984,'roberiogfreire@gmail.com',1),
('ROBERTA NUNES DE CAMPO VERDE',13577,'robertacampoverde@hotmail.com',1),
('ROBERTO CÉSAR BARBOSA DA SILVA',13826,'robertocesarsilva123@gmail.com',1),
('ROBERTO SINIBALDI',669,'robertos.jrengenharia@gmail.com',1),
('ROMINA LOPES DE MORAES',8856,'rominamoraes@hotmail.com',1),
('ROZINEIDE FIGUEIREDO RIBEIRO',16589,'jjoana_star@hotmail.com',1),
('SABRINA BEZERRA DE ALBUQUERQUE',15972,'sabrinabezerra@gmail.com',1),
('SANDRA MARIA SILVA MOREIRA',20907,'sandraacmmoreira@hotmail.com',1),
('SCARLETT AIRES VIANNA SILVEIRA',7335,'scarlett.aires@gmail.com',1),
('SHEILA PESSOA DE AZEVEDO RIBEIRO',22985,'parvartisheila@gmail.com',1),
('SHEYLA MARIA ROCHA FERREIRA',22068,'sheyla.mrf@gmail.com',1),
('SIMPLICIA MARIA AIRES VIANNA SINIBALDI',1346,'plicia@gmail.com',1),
('SOLANGE BEZERRA JUCÁ',22219,'sbjuca.sj@gmail.com',1),
('SONIA LEITE DA SILVA',22089,'silvanefro@gmail.com',1),
('SONIA MARIA CAMPOS CAMARA',19048,'soniamcamara@gmail.com',1),
('STENIO CARNEIRO MELLO MOREIRA',23601,'',1),
('SUELEN MOURA COSTA',10795,'suelenmc@gmail.com',1),
('SULENNE DA SILVA DE FREITAS',11660,'sulennefreitas@gmail.com',1),
('TERESA MARIA DA SILVA CÂMARA',3152,'teresa.camara@saude.ce.gov.br',1),
('TEREZA CRISTINA APOLIANO HONSI',22069,'tehonsi@gmail.com',1),
('TEREZA MARIA MOREIRA PESSOA',12776,'tmpessoa@icloud.com',1),
('TEREZA MARIA VASCONCELOS BASTOS',14461,'terezamariabastos@hotmail.com',1),
('TIAGO NOCRATO MOURA',19732,'tiagonocrato@hotmail.com',1),
('VALDILENE BARBOSA COSTA',6480,'val.bcosta@yahoo.com.br',1),
('VALÉRIA FERREIRA COSTA VILELLA',20710,'lella.100@hotmail.com',1),
('VALERIA RODRIGUES',22066,'ceixdobrasil@gmail.com',1),
('VANESSA FREIRE MEDEIROS',11666,'vanessafreire@hotmail.com',1),
('VANESSA LIMA MIYAZAWA',23291,'ruorapriiyaoliveira53556@gmail.com',1),
('VANIA REGINA MARQUES DE FREITAS',15701,'vaniafreitas@hotmail.com',1),
('VINICIUS ARAÚJO BEZERRA',9212,'vinicius.araujo.bezerra@gmail.com',1),
('WANDA MARIA BRAGA PARENTE',1012,'wandaparente@gmail.com',1),
('WERYSSON DANTAS SAMPAIO',21412,'emilianabarros@uol.com.br',1),
('YURI GADELHA ALVES BRANDÃO',13060,'yuri.cgdt@gmail.com',1);