begin transaction;

insert into materia_turma (turma_id, materia_id, professor_id) values
( (SELECT id FROM turma where codigo = 'ROMULO1'),(SELECT id FROM materia where nome = 'Sociopolítica II'),(SELECT id FROM professor where nome = 'LEANDRO BOTELHO AGUIAR') ),
( (SELECT id FROM turma where codigo = 'ROMULO1'),(SELECT id FROM materia where nome = 'Simbologia Teológica II'),(SELECT id FROM professor where nome = 'KELLY FERREIRA MARQUES BOTELHO AGUIAR') ),
( (SELECT id FROM turma where codigo = 'APIS1'),(SELECT id FROM materia where nome = 'Filosofia Moral'),(SELECT id FROM professor where nome = 'KELLY FERREIRA MARQUES BOTELHO AGUIAR') ),
( (SELECT id FROM turma where codigo = 'APIS1'),(SELECT id FROM materia where nome = 'Simbologia Teológica I'),(SELECT id FROM professor where nome = 'LEVI BAYDE RIBEIRO') ),
( (SELECT id FROM turma where codigo = 'APIS4'),(SELECT id FROM materia where nome = 'ISO I'),(SELECT id FROM professor where nome = 'KELLY FERREIRA MARQUES BOTELHO AGUIAR') ),
( (SELECT id FROM turma where codigo = 'APIS4'),(SELECT id FROM materia where nome = 'Psicologia'),(SELECT id FROM professor where nome = 'MARCUS CARVALHO DE MATOS') ),
( (SELECT id FROM turma where codigo = 'PITAGORAS2'),(SELECT id FROM materia where nome = 'Filosofia Acropolitana'),(SELECT id FROM professor where nome = 'LEANDRO BOTELHO AGUIAR') ),
( (SELECT id FROM turma where codigo = 'PITAGORAS2'),(SELECT id FROM materia where nome = 'ISO I'),(SELECT id FROM professor where nome = 'MARCUS CARVALHO DE MATOS') ),
( (SELECT id FROM turma where codigo = 'PITAGORAS2'),(SELECT id FROM materia where nome = 'Psicologia'),(SELECT id FROM professor where nome = 'SIMPLICIA MARIA AIRES VIANNA SINIBALDI') ),
( (SELECT id FROM turma where codigo = 'ENOCH2'),(SELECT id FROM materia where nome = 'Filosofia Acropolitana'),(SELECT id FROM professor where nome = 'MARCUS CARVALHO DE MATOS') ),
( (SELECT id FROM turma where codigo = 'ENOCH2'),(SELECT id FROM materia where nome = 'ISO I'),(SELECT id FROM professor where nome = 'KELLY FERREIRA MARQUES BOTELHO AGUIAR') ),
( (SELECT id FROM turma where codigo = 'ENOCH2'),(SELECT id FROM materia where nome = 'Psicologia'),(SELECT id FROM professor where nome = 'LEANDRO BOTELHO AGUIAR') ),
( (SELECT id FROM turma where codigo = 'PITAGORAS6'),(SELECT id FROM materia where nome = 'Filosofia Acropolitana'),(SELECT id FROM professor where nome = 'LEANDRO BOTELHO AGUIAR') ),
( (SELECT id FROM turma where codigo = 'PITAGORAS6'),(SELECT id FROM materia where nome = 'ISO I'),(SELECT id FROM professor where nome = 'KELLY FERREIRA MARQUES BOTELHO AGUIAR') ),
( (SELECT id FROM turma where codigo = 'PITAGORAS6'),(SELECT id FROM materia where nome = 'Psicologia'),(SELECT id FROM professor where nome = 'RAFAEL LIMA MONTENEGRO') ),
( (SELECT id FROM turma where codigo = 'PITAGORAS7'),(SELECT id FROM materia where nome = 'Filosofia Acropolitana'),(SELECT id FROM professor where nome = 'RAFAEL LIMA MONTENEGRO') ),
( (SELECT id FROM turma where codigo = 'PITAGORAS7'),(SELECT id FROM materia where nome = 'ISO I'),(SELECT id FROM professor where nome = 'ALINE MOTA ALBUQUERQUE LOUREIRO') ),
( (SELECT id FROM turma where codigo = 'PITAGORAS7'),(SELECT id FROM materia where nome = 'Psicologia'),(SELECT id FROM professor where nome = 'FLAVIA PINHEIRO DE ALENCAR PINTO') ),
( (SELECT id FROM turma where codigo = 'PITAGORAS3'),(SELECT id FROM materia where nome = 'Filosofia Acropolitana'),(SELECT id FROM professor where nome = 'RAFAEL LIMA MONTENEGRO') ),
( (SELECT id FROM turma where codigo = 'PITAGORAS3'),(SELECT id FROM materia where nome = 'ISO I'),(SELECT id FROM professor where nome = 'KELLY FERREIRA MARQUES BOTELHO AGUIAR') ),
( (SELECT id FROM turma where codigo = 'PITAGORAS3'),(SELECT id FROM materia where nome = 'Psicologia'),(SELECT id FROM professor where nome = 'SUELEN MOURA COSTA') ),
( (SELECT id FROM turma where codigo = 'PITAGÓRAS1'),(SELECT id FROM materia where nome = 'Filosofia Acropolitana'),(SELECT id FROM professor where nome = 'LEANDRO BOTELHO AGUIAR') ),
( (SELECT id FROM turma where codigo = 'PITAGÓRAS1'),(SELECT id FROM materia where nome = 'ISO I'),(SELECT id FROM professor where nome = 'MARCUS CARVALHO DE MATOS') ),
( (SELECT id FROM turma where codigo = 'PITAGÓRAS1'),(SELECT id FROM materia where nome = 'Psicologia'),(SELECT id FROM professor where nome = 'KELLY CABRAL') ),
( (SELECT id FROM turma where codigo = 'APIS7'),(SELECT id FROM materia where nome = 'Filosofia Acropolitana'),(SELECT id FROM professor where nome = 'LEANDRO BOTELHO AGUIAR') ),
( (SELECT id FROM turma where codigo = 'APIS7'),(SELECT id FROM materia where nome = 'ISO I'),(SELECT id FROM professor where nome = 'KELLY FERREIRA MARQUES BOTELHO AGUIAR') ),
( (SELECT id FROM turma where codigo = 'APIS7'),(SELECT id FROM materia where nome = 'Psicologia'),(SELECT id FROM professor where nome = 'KELLY CABRAL') ),
( (SELECT id FROM turma where codigo = 'APIS5'),(SELECT id FROM materia where nome = 'Filosofia Acropolitana'),(SELECT id FROM professor where nome = 'ANA CAROLINE ARAÚJO LIMA') ),
( (SELECT id FROM turma where codigo = 'APIS5'),(SELECT id FROM materia where nome = 'ISO I'),(SELECT id FROM professor where nome = 'MARCUS CARVALHO DE MATOS') ),
( (SELECT id FROM turma where codigo = 'APIS5'),(SELECT id FROM materia where nome = 'Psicologia'),(SELECT id FROM professor where nome = 'KELLY CABRAL') ),
( (SELECT id FROM turma where codigo = 'APIS6'),(SELECT id FROM materia where nome = 'Filosofia Acropolitana'),(SELECT id FROM professor where nome = 'KELLY CABRAL') ),
( (SELECT id FROM turma where codigo = 'APIS6'),(SELECT id FROM materia where nome = 'ISO I'),(SELECT id FROM professor where nome = 'LEVI BAYDE RIBEIRO') ),
( (SELECT id FROM turma where codigo = 'APIS6'),(SELECT id FROM materia where nome = 'Psicologia'),(SELECT id FROM professor where nome = 'RAFAEL LIMA MONTENEGRO') ),
( (SELECT id FROM turma where codigo = 'SIDHARTA1'),(SELECT id FROM materia where nome = 'ISO II - Corpo Prânico'),(SELECT id FROM professor where nome = 'LUIZ FERNANDO VIEIRA') ),
( (SELECT id FROM turma where codigo = 'SIDHARTA1'),(SELECT id FROM materia where nome = 'História da Filosofia Oriental'),(SELECT id FROM professor where nome = 'PAULO DE ALMEIDA AGUIAR') ),
( (SELECT id FROM turma where codigo = 'SIDHARTA2'),(SELECT id FROM materia where nome = 'História da Filosofia Antiga'),(SELECT id FROM professor where nome = 'MARCUS CARVALHO DE MATOS') ),
( (SELECT id FROM turma where codigo = 'SIDHARTA2'),(SELECT id FROM materia where nome = 'Simbologia Teológica V'),(SELECT id FROM professor where nome = 'KELLY FERREIRA MARQUES BOTELHO AGUIAR') ),
( (SELECT id FROM turma where codigo = 'SIDHARTA2'),(SELECT id FROM materia where nome = 'História da Filosofia Medieval'),(SELECT id FROM professor where nome = 'LEANDRO BOTELHO AGUIAR') )
;

commit transaction;