POST  https://nafortaleza.com.br:8443/pedagogia/api/materias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQG5hLmNvbS5iciIsImV4cCI6MTU0OTQ5OTA4NSwiUk9MRVMiOiJST0xFX1VTRVIifQ.2XumgaTZsfzUTodiZ1AMlTp-Ei0X5it5UJUWo-ZFCxnXgUeqIFDqYsuS7JtZW4tDqj47OwulPoX0OLAgjcNUgQ

{"nome": "Filosofia Moral","nivel": { "id": 2 },"temas": [
{"nome": "Tema 0 – Introdução","capitulos": [
{"nome": "O Que Entendemos por Moral Transcendental ?" },
{"nome": "A Importância da Filosofia Moral nas  Chamadas Escolas de Mistérios Tradicionais" },
{"nome": "O Papel da Moral no Budismo, Pitagorismo e Estoicismo" },
{"nome": "Os Budistas" },
{"nome": "Os Pitagóricos" },
{"nome": "Os Estóicos" }
]},{"nome": "Tema I","capitulos": [
{"nome": "Conceito de Bem e de Mal" },
{"nome": "Conceito de Vida e de Morte" },
{"nome": "Psique e Espírito" },
{"nome": "O Jogo de Maya" },
{"nome": "Thamas: Suas Vítimas e Seus Verdugos" },
{"nome": "Viveka e os Magos de Budham" },
{"nome": "O Homem e Seus Instintos, Sua Mente e o Real" },
{"nome": "O Homem e Seus Instintos" },
{"nome": "O Homem e Sua Mente" },
{"nome": "O Homem e o Real" }
]},{"nome": "Tema II","capitulos": [
{"nome": "Filosofia Búdhica - Filosofia Budista" },
{"nome": "Conceito de Mente e Valor dos Sentimentos no Budismo" },
{"nome": "Bhagavad Gîtâ: Análise e Comentários" },
{"nome": "Uttara Gîta: Análise e Comentários" },
{"nome": "A Voz do Silêncio" },
{"nome": "Esclarecimentos sobre a Seção LI, Tomo VI, A Doutrina Secreta: ¨A Doutrina do Olho e a Doutrina do Coração¨" }
]},{"nome": "Tema III","capitulos": [
{"nome": "A Filosofia Moral Grega" },
{"nome": "O Fenômeno Grego" },
{"nome": "Pitágoras" },
{"nome": "A Moral Pitagórica" },
{"nome": "Sócrates" },
{"nome": "A Moral Socrática" },
{"nome": "As Escolas Moralistas" },
{"nome": "Cínica e a Cirenáica" },
{"nome": "Antístenes" },
{"nome": "Arístipo de Cirene" },
{"nome": "Epicurismo: Epicuro e sua Doutrina" },
{"nome": "O Ceticismo: Pirrão, o Cético" }
]},{"nome": "Tema IV","capitulos": [
{"nome": "Estoicismo" },
{"nome": "Origens do Estoicismo" },
{"nome": "Doutrina Estóica" },
{"nome": "Física" },
{"nome": "Religião" },
{"nome": "Psicologia" },
{"nome": "Teoria do Conhecimento" },
{"nome": "Ética" },
{"nome": "Política e Direito" },
{"nome": "O Estoicismo do Império Romano" },
{"nome": "Marco Aurélio" }
]},{"nome": "Tema V","capitulos": [
{"nome": "Neoplatonismo: A Moral em Plotino" }
]},{"nome": "Tema VI","capitulos": [
{"nome": "A Filosofia Moral nas Culturas Americanas" },
{"nome": "Conceitos Morais Gerais nas Civilizações Americanas" },
{"nome": "Os Aztecas" },
{"nome": "O Calmecac e as Suas Disciplinas" },
{"nome": "A Moral entre os Aztecas" },
{"nome": "A Moral entre os Mayas" },
{"nome": "A Moral entre os Incas" },
{"nome": "Citações de Alguns Incas" }
]}]}
