POST  https://nafortaleza.com.br:8443/pedagogia/api/materias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQG5hLmNvbS5iciIsImV4cCI6MTU0OTcyNjg4NiwiUk9MRVMiOiJST0xFX1VTRVIifQ.SKYqXdxthos-zw1xaRzFbE0vh1bptMII9tTLHD8E_rZqKEh-sx3rK8lPIaqGyM1LKe88eLVdhq8QYkFrHnczCw

{"nome": "História da Filosofia Oriental","nivel": { "id": 2 },"temas": [
{"nome": "Tema 1 – Introducción","capitulos": [
{"nome": "Contactos de Occidente com La Filosofía Oriental" },
{"nome": "Grecia y Romna" },
{"nome": "Neoplatónicos y Gnósticos" },
{"nome": "Edad Media" },
{"nome": "El Renacimiento y La Moda China" },
{"nome": "El Renacimiento y el Próximoy Medio Oriente" },
{"nome": "Pioneros del Orientalismo" },
{"nome": "Alemania" },
{"nome": "Europa" },
{"nome": "Filosofía Oriental" }
]},{"nome": "Tema 2 – India","capitulos": [
{"nome": "Características Generales de Su Filosofía" },
{"nome": "Cronología Del Pensamiento Indio" },
{"nome": "Período Védico" },
{"nome": "Los Arios" },
{"nome": "El Veda" },
{"nome": "Rig Veda" },
{"nome": "Sama Veda" },
{"nome": "Yajur Veda" },
{"nome": "Atharva Veda" },
{"nome": "Los Brahmanas" },
{"nome": "Los Aranyakas" },
{"nome": "Los Upanishads" },
{"nome": "Los Dioses Del Veda" },
{"nome": "Cosmogonía" },
{"nome": "Los Ritos y El Conocimiento (del sacrifício a la mística)" },
{"nome": "Los Ideales Védicos em La Política y em La Ética" },
{"nome": "El Dharma" },
{"nome": "Artha" },
{"nome": "Kama" },
{"nome": "Las Castas" },
{"nome": "Período Épico, Sutra y Escolástico: El Hinduísmo" },
{"nome": "La Literatura Sagrada Hinduista" },
{"nome": "El Veda" },
{"nome": "Upanishads Postvédicos" },
{"nome": "La Epopeya" },
{"nome": "El Mahabharata" },
{"nome": "El Ramayana" },
{"nome": "Los Sutras" },
{"nome": "Los Puranas" },
{"nome": "El Período Escolástico" },
{"nome": "Filosofía Hinduista" },
{"nome": "Conceptos Generales" },
{"nome": "El Origen del Universo" },
{"nome": "Kritayuga" },
{"nome": "Tretayuga" },
{"nome": "Dvaparayuga" },
{"nome": "Kaliyuga" },
{"nome": "Karma" },
{"nome": "Samsara" },
{"nome": "La Liberacíon" },
{"nome": "Karma Marga" },
{"nome": "Bakti Marga" },
{"nome": "Gnani Marga" },
{"nome": "Raja Marga" },
{"nome": "Las Seis Escuelas Ortodoxas de Filosofía" },
{"nome": "La Escuela Vaiseshika" },
{"nome": "Escuela Nyaya" },
{"nome": "Escuela Sankhya" },
{"nome": "El Yoga" },
{"nome": "Las Ocho Etapas o Disciplinas" },
{"nome": "Yama" },
{"nome": "Niyama" },
{"nome": "Asana (Postura)" },
{"nome": "Pranayana" },
{"nome": "Pratyehara" },
{"nome": "Dharana" },
{"nome": "Dhyana" },
{"nome": "Samadhi" },
{"nome": "El Tantrismo" },
{"nome": "La Mimansa" },
{"nome": "El Vedanta" },
{"nome": "Sankara" },
{"nome": "Ramanuja" },
{"nome": "Madhva" },
{"nome": "Nimbarka" },
{"nome": "Vallabha" },
{"nome": "Sectas Del Hinduísmo" },
{"nome": "Shivaísmo" },
{"nome": "Los Saktas" },
{"nome": "Vishnuismo" },
{"nome": "Sectas Vishnuítas" },
{"nome": "Srivaishnavas" },
{"nome": "Ramanandis" },
{"nome": "Krishnaítas" },
{"nome": "Las Sectas Krishnaítas" },
{"nome": "Los Nimbarkas" },
{"nome": "Los Vallabhacharyas" },
{"nome": "Chaitanya" },
{"nome": "El Hinduísmo Moderno" },
{"nome": "La Sociedad" },
{"nome": "El Bhahmacharin" },
{"nome": "El Grihasta" },
{"nome": "El Vanaprastha" },
{"nome": "El Sannyasin" },
{"nome": "La Moral" },
{"nome": "(Del Siglo XVIII em Adelante)" },
{"nome": "El Brahmansamaj" },
{"nome": "Ramakrishna" },
{"nome": "El Ariasamaj" },
{"nome": "Vivekananda" }
]},{"nome": "Tema 3 – Las Filosofías Heréticas","capitulos": [
{"nome": "Los Sikhs" },
{"nome": "Kabir" },
{"nome": "Nanak" },
{"nome": "Jainismo" },
{"nome": "Metafísica y Ascesis" }
]},{"nome": "Tema 4 – Budismo","capitulos": [
{"nome": "Introduccción" },
{"nome": "Buda" },
{"nome": "El Dolor" },
{"nome": "La Liberación" },
{"nome": "Vidas Anteriores" },
{"nome": "Vida Presente" },
{"nome": "Vidas Futuras" },
{"nome": "La Moral" },
{"nome": "El ¨Agnosticismo¨ y el ¨Ateísmo¨ Budista" },
{"nome": "Los Tres Vehículos" },
{"nome": "Pequeno Vehículo o Hinayana" },
{"nome": "La Cesta de La Disciplina" },
{"nome": "La Cesta de Los Discursos" },
{"nome": "La Cesta de Los Dogmas" },
{"nome": "Gran Veículo o Mahayana" },
{"nome": "El Loto de la Buena Ley" },
{"nome": "La Descripción Detallada Del País Puro" },
{"nome": "Lalita-Vistara" },
{"nome": "La Perfección Del Conocimiento" },
{"nome": "Los Madhyamikas o ¨Escuela Del Medio¨" },
{"nome": "Los Yogacharyas o ¨Escuela de la Conciencia¨" },
{"nome": "Vehículo de Diamante o Vajrayana" },
{"nome": "Budismo Chino y Sus Escuelas" },
{"nome": "La Escuela de la Disciplina o Lu-Tsong" },
{"nome": "La Escuela del País Puro o Ching-Tu-Tsong" },
{"nome": "La Escuela de la Meditación (Chan)                                                                                                                                        Escuela de la Espiritualidad (Hin-Tsong)" },
{"nome": "La Escuela del Saber y de la Absorción (Tien-Tai)" },
{"nome": "La Escuela de los Secretos (Mi-Tsong)" },
{"nome": "Budismo Japoneses y Sus Sectas" },
{"nome": "Las Sectas de Nara" },
{"nome": "La Secta Hosso" },
{"nome": "La Secta Kegon" },
{"nome": "Las Sectas de Heian (794-1.192) o Kyoto" },
{"nome": "La Secta Tendai" },
{"nome": "La Secta Shingon" },
{"nome": "Las  NiSectas de Kamakura" },
{"nome": "El Zen" },
{"nome": "Las Sectas Amidistas" },
{"nome": "El Jodoshu o Escuela del Pais Puro" },
{"nome": "El Jodo-Shinshu o Verdadera Escuela Del Pais Puro" },
{"nome": "La Secta Nichiren" },
{"nome": "Budismo Tibetano" }
]},{"nome": "Tema 5 – China","capitulos": [
{"nome": "La China Arcaica – Textos Clásicos" },
{"nome": "El Yi King o ¨Libro de las Mutaciones¨" },
{"nome": "El Chu King o ¨Libro de los Documentos¨" },
{"nome": "El Che King o ¨Libro de las Odas¨" },
{"nome": "El Li-Ki" },
{"nome": "Las Ideas Centrales" },
{"nome": "Armonía de la Naturaleza y la Ley como Reflejo.                                                                                                         Adivinación. Sacerdócio" },
{"nome": "Adivinación" },
{"nome": "El Príncipe. El Sacerdote." },
{"nome": "Confucio" },
{"nome": "Confucio y sus Obras" },
{"nome": "El Luen Yu" },
{"nome": "El Chong Yong" },
{"nome": "El Ta-Hio" },
{"nome": "El Mong-Tse" },
{"nome": "Ética y Política" },
{"nome": "El Hombre Perfecto: El Sabio" },
{"nome": "Discípulos de Confucio:" },
{"nome": "Mong-Tse" },
{"nome": "Siun-Tse" },
{"nome": "Neo-Confucianismo" },
{"nome": "El Tao y Lao-Tse" },
{"nome": "Lao-Tse. Vida y Obras" },
{"nome": "El Tao-te-King" },
{"nome": "El Taoísmo y Otros Sabios" },
{"nome": "El Tao" },
{"nome": "Moral y Magia" },
{"nome": "Otras Escuelas Chinas / Mo-Tse" }
]},{"nome": "Tema 6 – Japón","capitulos": [
{"nome": "Sincretismo y Nacionalismos" },
{"nome": "Los Libros ¨Shinto¨" },
{"nome": "El Kojiki" },
{"nome": "El Nihongi" },
{"nome": "El Engishiki" },
{"nome": "Fuerzas de La Naturaleza" },
{"nome": "La Moral Shintoísta, Pureza Ritual:" },
{"nome": "Evolución Histórica:" },
{"nome": "El Zen:" }
]},{"nome": "Tema 7 – Irán","capitulos": [
{"nome": "Los Iranios:" },
{"nome": "Zoroastro y El Avesta:" },
{"nome": "Los Textos Litúrgicos" },
{"nome": "El Yasna o Libro de los Sacrificios" },
{"nome": "El Videvdat o Vendidad" },
{"nome": "El Visprat o Vispered" },
{"nome": "El Pequeño Avesta o Khordah Avesta" },
{"nome": "Zofroastro:" },
{"nome": "La Doctrina Moral de Zoroastro:" },
{"nome": "El Dualismo: Guerra Universal Entre El Bien y El Mal" },
{"nome": "Los Parsis" },
{"nome": "Breve Reseña de La Historia del Zoroastrismo" }
]},{"nome": "Tema 8 – Mesopotamia","capitulos": [
{"nome": "Sumerios y Semitas:" },
{"nome": "Textos Sagrados" },
{"nome": "La Epopeya de Gilgamesh" },
{"nome": "El Poema de La Creación" },
{"nome": "Poema de Em-Ki y Ninursag" },
{"nome": "Poema de Dumuzi e Inana" },
{"nome": "Moral y Metafísica: La Ley" },
{"nome": "El Mal. Los Sacrificios" },
{"nome": "El Devenir" },
{"nome": "Los Cultos Religiosos – Los Sacerdotes. Las Plegarias" },
{"nome": "Magia Y Adivinación" },
{"nome": "Supervivencia Histórica de Babilonia:" }
]},{"nome": "Tema 9 – Egipto","capitulos": [
{"nome": "Introducción" },
{"nome": "Mito y Rito" },
{"nome": "Relaciones entre los Hombres y los Dioses" },
{"nome": "La Filosofía Hermética" }
]},{"nome": "Tema 10 – Islam y Esoterismo Islámico","capitulos": [
{"nome": "El Sufismo:" },
{"nome": "Doctrina Filosófica" },
{"nome": "LaUnidad Divina" },
{"nome": "El Espíritu" },
{"nome": "El Hombre Universal" },
{"nome": "El Intelecto" }
]},{"nome": "Tema 11 – Lá Cábala","capitulos": [
{"nome": "Introducción y Desarrollo Histórico:" },
{"nome": "La Doctrina:" },
{"nome": "La Cábala Práctica" },
{"nome": "La Cábala Dogmática" },
{"nome": "La Cábala Literal" },
{"nome": "La Cábala No-Escrita" },
{"nome": "Atziluth" },
{"nome": "Briah" },
{"nome": "Yetzirah" },
{"nome": "Assiah" },
{"nome": "El Árbol de La Vida o Árbol Sephirotal:" },
{"nome": "La Cábala Literal" },
{"nome": "La Cábala Dogmática:" },
{"nome": "La Cábala Práctica" },
{"nome": "Gematria:" },
{"nome": "Notaricon:" },
{"nome": "Temura:" },
{"nome": "El Nombre de Dios" }
]}]}
