POST  https://nafortaleza.com.br:8443/pedagogia/api/materias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQG5hLmNvbS5iciIsImV4cCI6MTU0OTQ5OTA4NSwiUk9MRVMiOiJST0xFX1VTRVIifQ.2XumgaTZsfzUTodiZ1AMlTp-Ei0X5it5UJUWo-ZFCxnXgUeqIFDqYsuS7JtZW4tDqj47OwulPoX0OLAgjcNUgQ

{"nome": "Psicologia","nivel": { "id": 2 },"temas": [
{"nome": "Tema I","capitulos": [
{"nome": "Introdução" }
]},{"nome": "Tema II","capitulos": [
{"nome": "Consciência" }
]},{"nome": "Tema III","capitulos": [
{"nome": "Atenção" }
]},{"nome": "Tema IV","capitulos": [
{"nome": "Memória" }
]},{"nome": "Tema V","capitulos": [
{"nome": "Inteligência" }
]},{"nome": "Tema VI","capitulos": [
{"nome": "Imaginação" }
]},{"nome": "Tema VII","capitulos": [
{"nome": "Hábitos" }
]},{"nome": "Tema VIII","capitulos": [
{"nome": "Sensações" }
]},{"nome": "Tema IX","capitulos": [
{"nome": "Fenômenos  Afetivos" }
]},{"nome": "Tema X","capitulos": [
{"nome": "Personalidade" }
]},{"nome": "Tema XI","capitulos": [
{"nome": "Vontade" }
]},{"nome": "Tema XII","capitulos": [
{"nome": "Psicanálise e Psicossíntese" },
{"nome": "Consciente e Inconsciente" },
{"nome": "Hipnose e Catarses" },
{"nome": "Formação de Personalidade" },
{"nome": "Princípios do Prazer" },
{"nome": "Vida Onírica" },
{"nome": "Energia Psíquica" },
{"nome": "Os Três Níveis do Sistema Psicológico" },
{"nome": "Psicanálise" },
{"nome": "Disidências e Aportes" },
{"nome": "A Psicanálise Hoje" },
{"nome": "Possibilidades Afetivas" },
{"nome": "Alguns Aportes à Teoria da Síntese" }
]},{"nome": "Tema XIII","capitulos": [
{"nome": "Parapsicologia: I-Introdução" },
{"nome": "Aproximação ao Mundo Astral" },
{"nome": "Estrutura do Astral" },
{"nome": "Aproximação ao Mundo Mental" },
{"nome": "O Veículo Manas" },
{"nome": "Consciência de Vigília" },
{"nome": "A Consciência Onírica" },
{"nome": "Parapsicologia:II-Os Fenômenos" },
{"nome": "Fenômenos de Desdobramento" },
{"nome": "Mensagens Oníricas" },
{"nome": "Os Arquivos do Passado" },
{"nome": "Psicometria" },
{"nome": "Precognição e Liberdade" },
{"nome": "Clarividência" },
{"nome": "Telepatia" },
{"nome": "Dom de Línguas" },
{"nome": "Hipnotismo" },
{"nome": "Mesmerismo" },
{"nome": "Médiuns" },
{"nome": "Transe" },
{"nome": "Conclusão" }
]}]}
