POST  https://nafortaleza.com.br:8443/pedagogia/api/materias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQG5hLmNvbS5iciIsImV4cCI6MTU0OTQ5OTA4NSwiUk9MRVMiOiJST0xFX1VTRVIifQ.2XumgaTZsfzUTodiZ1AMlTp-Ei0X5it5UJUWo-ZFCxnXgUeqIFDqYsuS7JtZW4tDqj47OwulPoX0OLAgjcNUgQ

{"nome": "Simbologia Teológica V","nivel": { "id": 2 },"temas": [
{"nome": "Tema I – Simbologia Teológica na América central","capitulos": [
{"nome": "Cultura Olmeca" },
{"nome": "Teotihuacan" },
{"nome": "Tula" },
{"nome": "Complexo Chichimeca" },
{"nome": "Aztecas" },
{"nome": "Os Deuses do Panteão Nahuatl" },
{"nome": "Hue Hue Teotl" },
{"nome": "Xolotl" },
{"nome": "Tlaloc" },
{"nome": "Tlachitonatiuh" },
{"nome": "Cuauhtemoc" },
{"nome": "Xochipilli" },
{"nome": "Tamoanchan" },
{"nome": "Ollin Tonatiuh" },
{"nome": "Tialtecuhtli" },
{"nome": "Chalchiutlicue" },
{"nome": "Micantecuhtli" },
{"nome": "Huitzlopochtli" },
{"nome": "Xipe Totec" },
{"nome": "Tezcatlipoca" },
{"nome": "Quetzalcoatl" },
{"nome": "Malinal Xochitl" },
{"nome": "Xiuhtecuhtli" },
{"nome": "Tlazolteotli" },
{"nome": "Jaguar ou Tigre" },
{"nome": "Iztlacoliuhqui" },
{"nome": "Tula" },
{"nome": "Homem – Jaguar – Serpente" },
{"nome": "Relação do Panteão Nahualt com Outros Panteões Americanos" },
{"nome": "Panteão Chibcha" },
{"nome": "Panteão Tiahuanacota" },
{"nome": "Cultura de Oaxaca" },
{"nome": "Zapotecas" },
{"nome": "Cocijo" },
{"nome": "Pitao Cozobi" },
{"nome": "O Deus Morcego" },
{"nome": "O Jaguar" },
{"nome": "A Deusa 13ª Serpente" },
{"nome": "O Deus a 5ª Flor" },
{"nome": "Xipe Totec" },
{"nome": "Quetzalcoatl" },
{"nome": "Deus do Fogo" },
{"nome": "Comentário do Instrutor JAL Sobre o Livro ¨O Universo de Quetzalcoatl¨ (De Laurette Séjourné)" },
{"nome": "Mixtecas" },
{"nome": "Culturas do Golfo" },
{"nome": "A Cultura Huazteca" },
{"nome": "A Cultura de Vera Cruz" },
{"nome": "Os Olmecas Históricos" },
{"nome": "Culturas do Ocidente" },
{"nome": "Culturas do Norte do México" },
{"nome": "Zacatecas" },
{"nome": "Durango" },
{"nome": "Chichuaha" },
{"nome": "Área Maia" },
{"nome": "Período Pré-Classico" },
{"nome": "Período Clássico" },
{"nome": "Período Pós Clássico" },
{"nome": "Religião e Deidade" },
{"nome": "Itzamná" },
{"nome": "Chaac" },
{"nome": "Deus do Milho" },
{"nome": "Ah Puch" },
{"nome": "Xamanek" },
{"nome": "Ek Chuah" },
{"nome": "Kukulcan" },
{"nome": "Ixchel" },
{"nome": "Ixtab" },
{"nome": "O Popol Vuh" },
{"nome": "Alguns Aspectos Simbólicos do Popol Vuh" },
{"nome": "Comentários de JAL sobre o Livro ¨Popol Vuh¨" },
{"nome": "Capítulo VII" },
{"nome": "Capítulo" },
{"nome": "Capítulo XXI" },
{"nome": "Capítulo XXIV" },
{"nome": "Capítulo XXX" },
{"nome": "Iqui Balam" },
{"nome": "Viagem dos Pais a Xibalba" },
{"nome": "Nascimento de Hunapú e Ixbalanqué" },
{"nome": "Relato Sobre Vucub Caquix (Principal Guacamayo)" }
]},{"nome": "Tema II – Simbologia Teológica na América do Sul","capitulos": [
{"nome": "Equador" },
{"nome": "Colômbia" },
{"nome": "Cultura de San Agustín" },
{"nome": "Peru" },
{"nome": "Chavín" },
{"nome": "Cultura Chimú" },
{"nome": "Cultura Incaica" },
{"nome": "Paracas" },
{"nome": "Nasca" },
{"nome": "Cultura Mochica" },
{"nome": "Bolívia" },
{"nome": "Tiahuanaco" }
]}]}
