POST  https://nafortaleza.com.br:8443/pedagogia/api/materias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQG5hLmNvbS5iciIsImV4cCI6MTU0OTQ5OTA4NSwiUk9MRVMiOiJST0xFX1VTRVIifQ.2XumgaTZsfzUTodiZ1AMlTp-Ei0X5it5UJUWo-ZFCxnXgUeqIFDqYsuS7JtZW4tDqj47OwulPoX0OLAgjcNUgQ

{"nome": "Simbologia Teológica III","nivel": { "id": 2 },"temas": [
{"nome": "Tema 0 – Prólogo","capitulos": [
{"nome": "Introdução ao Simbolismo  Teológico do Extermo Oriente" }
]},{"nome": "Tema I","capitulos": [
{"nome": "INDIA" },
{"nome": "Introdução" },
{"nome": "Brahmanismo" },
{"nome": "A Casta Guerreira" },
{"nome": "Indra" },
{"nome": "Mitra e Varuna" },
{"nome": "Varuna" },
{"nome": "Nasaiyas ou Azvins" },
{"nome": "Chakravartin" },
{"nome": "Ashvamedha" },
{"nome": "A Casta Brahmânica:" },
{"nome": "Agni" },
{"nome": "Soma" },
{"nome": "Savitri" },
{"nome": "Surya" },
{"nome": "Ushas" },
{"nome": "Prajapati" },
{"nome": "Aditi" },
{"nome": "As Castas Populares:" },
{"nome": "Asuras" },
{"nome": "Rakshasas" },
{"nome": "Pishakas" },
{"nome": "Nagas" },
{"nome": "Gandharvas" },
{"nome": "Apsaras" },
{"nome": "Rudra" },
{"nome": "Conceitos Metafísicos e Cosmogônicos do Brahmanismo:" },
{"nome": "Brahman" },
{"nome": "Purusha e Prakriti" },
{"nome": "Hiranya Garba" },
{"nome": "Yama" },
{"nome": "Atman" },
{"nome": "Ciclo do Fogo Mental" },
{"nome": "Hinduísmo" },
{"nome": "Brahma" },
{"nome": "Sarasvati" },
{"nome": "Vishnu" },
{"nome": "Shiva" },
{"nome": "Budismo" }
]},{"nome": "Tema II","capitulos": [
{"nome": "CHINA" },
{"nome": "Introdução" },
{"nome": "Deidades do Céu:" },
{"nome": "Augusto de Jade" },
{"nome": "Deidades Estelares e da Natureza:" },
{"nome": "Sol" },
{"nome": "Lua" },
{"nome": "Chuva, Trovão e Vento" },
{"nome": "Reis-Dragões" },
{"nome": "Deus das Letras (We T'Chang) e o Deus dos Exames (K'Dei Sing)" },
{"nome": "Deus da Felicidade" },
{"nome": "A Tecedeira Celeste" },
{"nome": "Deidades Populares e Deidades para os Homens:" },
{"nome": "Os Deuses do Monte T'ai-chan" },
{"nome": "Deuses das Muralhas e das Covas" },
{"nome": "Deuses do Lar" },
{"nome": "Deuses das Portas" },
{"nome": "Deus da Riqueza" },
{"nome": "Imperador Kuan-ti" },
{"nome": "Os Oito Imortais - Pa-sien" },
{"nome": "Deuses das Profissões" },
{"nome": "Inferno" },
{"nome": "Adendo" }
]},{"nome": "Tema III","capitulos": [
{"nome": "JAPÃO" },
{"nome": "Introdução" },
{"nome": "Elementos Fundamentais da Simbologia Japonesa:" },
{"nome": "Os Kami" },
{"nome": "A Região dos Mortos" },
{"nome": "Cosmogênese e Antropogênese:" },
{"nome": "Izanagi e Izanami" },
{"nome": "Susanoo" },
{"nome": "O-Kuni-Nushi" },
{"nome": "Ninigi" },
{"nome": "Outros Deuses:" },
{"nome": "Símbolos do Sol:" },
{"nome": "Amaterasu" },
{"nome": "Wakahiru-me" },
{"nome": "Tsuki-Yomi" },
{"nome": "Kami-Nari" },
{"nome": "Dedidades da Chuva" },
{"nome": "Deidades do Vento" },
{"nome": "Deuses das Montanhas" },
{"nome": "Dedidades dos Rios" },
{"nome": "Deidades do Mar" },
{"nome": "Deus do Fogo - Ho-Musubi" },
{"nome": "Deuse s do Caminho" },
{"nome": "Deuses Agrestes" },
{"nome": "Uke-Mochi" },
{"nome": "Divindades das Diferentes Partes do Lar" }
]}]}
