POST  https://nafortaleza.com.br:8443/pedagogia/api/materias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQG5hLmNvbS5iciIsImV4cCI6MTU0OTQ5OTA4NSwiUk9MRVMiOiJST0xFX1VTRVIifQ.2XumgaTZsfzUTodiZ1AMlTp-Ei0X5it5UJUWo-ZFCxnXgUeqIFDqYsuS7JtZW4tDqj47OwulPoX0OLAgjcNUgQ

{"nome": "Simbologia Teológica VI e VII","nivel": { "id": 2 },"temas": [
{"nome": "Tema 6 – Simbologia Teológica da Europa","capitulos": [
{"nome": "Celtas" },
{"nome": "Pré-Celtas" },
{"nome": "Outros Símbolos" },
{"nome": "Os Celtas Continentais" },
{"nome": "Os Gálios: Suas Divindades e Símbolos" },
{"nome": "Deuses Antropomórlicos Gálio-Romanos" },
{"nome": "Mercúrio Gálio" },
{"nome": "Ogmio" },
{"nome": "Apolo" },
{"nome": "Marte" },
{"nome": "Minerva" },
{"nome": "Júpiter Gálio" },
{"nome": "Dis Pare" },
{"nome": "Sucellus" },
{"nome": "Cernunno (O Cornudo)" },
{"nome": "Deusa Mãe" },
{"nome": "As Mães" },
{"nome": "Celtas insulares (Grã-Bretanha e Irlanda)" },
{"nome": "Panteão Insular" },
{"nome": "Govannon" },
{"nome": "Lluoo ou Nuoo" },
{"nome": "Amaethon" },
{"nome": "Gwidion" },
{"nome": "Arianrod" },
{"nome": "Ciclo de Artur" },
{"nome": "Artur" },
{"nome": "Epopéia Mítica da Irlanda (O Ciclo                                                                                                                                    das Invasões)" },
{"nome": "Heróis" },
{"nome": "Os Germânicos" },
{"nome": "Alemanha e Países Escandinavos" },
{"nome": "Cosmogênese e Antropogênese" },
{"nome": "Panteão Germânico" },
{"nome": "Wotan / Odin" },
{"nome": "Donar-Thor" },
{"nome": "Tiuz-Tyr" },
{"nome": "Loki" },
{"nome": "Balder" },
{"nome": "Os Vanes" },
{"nome": "Deusas" },
{"nome": "Os Espíritos" },
{"nome": "As Normas" },
{"nome": "Elfos e Anões" },
{"nome": "Os Iberos" },
{"nome": "Tartessos" },
{"nome": "Antiguidade de Tartessos" },
{"nome": "Alfabeto Tartéssico" },
{"nome": "Religião" },
{"nome": "Simbologia dos Iberos" },
{"nome": "Religião Ibérica" },
{"nome": "Sibologia Ugro-Finesa" },
{"nome": "O Kalevala" },
{"nome": "A Magia" },
{"nome": "Elementos Mágicos no Kalevala" },
{"nome": "Deuses do Kalevala" },
{"nome": "Celestes" },
{"nome": "Da Terra e das Águas" },
{"nome": "Mundo Infernal ou Reino dos Mortos" },
{"nome": "Aminismo" },
{"nome": "Mitos" }
]},{"nome": "Tema 7 – Simbologia Teológica Cristã e Medieval","capitulos": [
{"nome": "Introdução" },
{"nome": "Os Essênios" },
{"nome": "Formas Especiais de Vida" },
{"nome": "Doutrina" },
{"nome": "O Segredo" },
{"nome": "Os Terapêutas" },
{"nome": "Doutrina" },
{"nome": "Cristianismo" },
{"nome": "O Cristo Histórico" },
{"nome": "O Cristo Mítico" },
{"nome": "O Cristo Místico" },
{"nome": "O Sacrifício" },
{"nome": "Ressurreição e Ascensão" },
{"nome": "Trindade" },
{"nome": "Preces" },
{"nome": "Sacramentos" },
{"nome": "Revelação" },
{"nome": "Lugares e Objetos Sagrados" },
{"nome": "Simbologia do Islã" },
{"nome": "O Corão" },
{"nome": "Alá" },
{"nome": "O Universo" },
{"nome": "O Inferno" },
{"nome": "O Paraíso" },
{"nome": "A Criação do Homem" },
{"nome": "Extrações Bíblicas" },
{"nome": "A Moral" },
{"nome": "Peregrinação à Meca" },
{"nome": "A Guerra Santa" },
{"nome": "A Gnose e os Gnósticos" },
{"nome": "Simão, o Mago" },
{"nome": "Basílides, o Egípcio" },
{"nome": "Valentinus" },
{"nome": "A Pistis Sofia" },
{"nome": "Os Ofitas" },
{"nome": "O Simbolismo Gnóstico" },
{"nome": "Cátaros e Templários" },
{"nome": "Os Cátaros" },
{"nome": "A Doutrina" },
{"nome": "A Iniciação – A ¨Endura¨" },
{"nome": "Os Ritos Cátaros" },
{"nome": "Os Templários" },
{"nome": "A Iniciação e a Doutrina" },
{"nome": "Símbolos Próprios dos Templários" },
{"nome": "A Tradição Hermética: Alquimia" },
{"nome": "Renascimento" },
{"nome": "Rosacruzes" },
{"nome": "A Franco Maçonaria" }
]}]}
