POST  https://nafortaleza.com.br:8443/pedagogia/api/materias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQG5hLmNvbS5iciIsImV4cCI6MTU0OTQ5OTA4NSwiUk9MRVMiOiJST0xFX1VTRVIifQ.2XumgaTZsfzUTodiZ1AMlTp-Ei0X5it5UJUWo-ZFCxnXgUeqIFDqYsuS7JtZW4tDqj47OwulPoX0OLAgjcNUgQ

{"nome": "Simbologia Teológica II","nivel": { "id": 2 },"temas": [
{"nome": "Tema II","capitulos": [
{"nome": "Simbologia Teológica na Ásia Menor" },
{"nome": "Introdução" },
{"nome": "Sumer" },
{"nome": "Assíria - Babilônia" },
{"nome": "Os Grandes Deuses:" },
{"nome": "Anu" },
{"nome": "Bel" },
{"nome": "Ea" },
{"nome": "Marduk" },
{"nome": "Ashur" },
{"nome": "Os Deuses Estelares:" },
{"nome": "Sin" },
{"nome": "Samash" },
{"nome": "Ishtar" },
{"nome": "Mitos e Relatos Heróicos:" },
{"nome": "O Dilúvio" },
{"nome": "Etana" },
{"nome": "Adapa" },
{"nome": "Gilgamesh" },
{"nome": "Influências da Áres Mesopotâmica" },
{"nome": "Elamitas" },
{"nome": "Hititas" },
{"nome": "Mitos Cosmogônicos e Teogônicos Hurritas:" },
{"nome": "O Mito da Realeza nos Céus" },
{"nome": "O Canto de Ulikumi" },
{"nome": "O Mito da Serpente Illuyanka" },
{"nome": "O Mito de Telepinu" },
{"nome": "Hopolatria" },
{"nome": "Síria e Fenícia" },
{"nome": "Panteão de Ugarit:" },
{"nome": "El" },
{"nome": "Baal" },
{"nome": "Anat" },
{"nome": "Astarte" },
{"nome": "Asherat" },
{"nome": "Elat" },
{"nome": "Deuses Fenícios do 1º Milênio" },
{"nome": "Deuses de Cartago:" },
{"nome": "Baal Amon" },
{"nome": "Adonis e Eshmun" },
{"nome": "Bes" },
{"nome": "Tanit" },
{"nome": "Simbolismo da Pérsia Antiga: Os Iranianos" },
{"nome": "Introdução" },
{"nome": "Religião Avestica" },
{"nome": "  O Fogo" },
{"nome": "O Haoma,,47 a 48" },
{"nome": "Mitra e Varuna; Indra e os Nasatyas" },
{"nome": "              Deuses Menores,48," },
{"nome": "Os Mags (ou Magos)" },
{"nome": "Religião Mazdeísta" },
{"nome": "Ahura Mazda" },
{"nome": "A Reforma de Zoroastro" },
{"nome": "O Mitraísmo e os Símbolos Religiosos sob a Influência das Arsácidas" },
{"nome": "Mitra" },
{"nome": "Deidades e Símbolos dos Sassanidas" },
{"nome": "Os Amesha Spentas ou Amchaspendes" },
{"nome": "Os Yazatas e os Fravarhis" },
{"nome": "Devas" },
{"nome": "Maniqueísmo" },
{"nome": "Cosmogonia  Iraniana" },
{"nome": "Idéias Sobre a Vida Eterna" },
{"nome": "Mulçumanos na Pérsia" }
]}]}
