POST  https://nafortaleza.com.br:8443/pedagogia/api/materias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQG5hLmNvbS5iciIsImV4cCI6MTU0OTQ5OTA4NSwiUk9MRVMiOiJST0xFX1VTRVIifQ.2XumgaTZsfzUTodiZ1AMlTp-Ei0X5it5UJUWo-ZFCxnXgUeqIFDqYsuS7JtZW4tDqj47OwulPoX0OLAgjcNUgQ

{"nome": "Simbologia Teológica IV","nivel": { "id": 2 },"temas": [
{"nome": "Tema I","capitulos": [
{"nome": "Simbologia Teológica na Grécia" },
{"nome": "Simbologia Pré-Helênica" },
{"nome": "                  A Grande Deusa Mãe" },
{"nome": "                 Simbologia na Grécia Clássica" },
{"nome": "                  Teogonia" },
{"nome": "A Primeira Dinastia Olimpiana" },
{"nome": "A Segunda Dinastia Olimpiana" },
{"nome": "A Terceira Dinastia Olimpiana" }
]},{"nome": "Tema II - O Panteão Grego","capitulos": [
{"nome": "                  Divindades Primordiais Olimpianas" },
{"nome": "Zeus" },
{"nome": "Hera" },
{"nome": "Atena" },
{"nome": "Apolo" },
{"nome": "Artemisa" },
{"nome": "Hermes" },
{"nome": "Ares" },
{"nome": "Hefestos" },
{"nome": "Afrodite" },
{"nome": "Eros" },
{"nome": "Cáritas" },
{"nome": "Poseidon" },
{"nome": "Héstia" },
{"nome": "Divindades Primordiais da Terra" },
{"nome": "Cibele" },
{"nome": "Deméter" },
{"nome": "Dionísio" },
{"nome": "Divindades Primordiais do Mundo Subterrâneo" },
{"nome": "Hades" },
{"nome": "Hécate" },
{"nome": "Tânatos" },
{"nome": "Divindades Secundárias do Olimpo" },
{"nome": "Têmis" },
{"nome": "Íris" },
{"nome": "Hebe" },
{"nome": "Ganimedes" },
{"nome": "As Horas" },
{"nome": "Divindades Estelares" },
{"nome": "Hélios" },
{"nome": "Selene" },
{"nome": "Eos" },
{"nome": "Constelações,,,29 a 31" },
{"nome": "Órion" },
{"nome": "As Plêiades" },
{"nome": "As Híades" },
{"nome": "Deidades dos Ventos" },
{"nome": "Bóreas" },
{"nome": "Zéfiro" },
{"nome": "Euro" },
{"nome": "Noto" },
{"nome": "Éolo" },
{"nome": "Ventos Tempestuosos" },
{"nome": "Quimera" },
{"nome": "As Hárpias" },
{"nome": "Deidades das Águas e do Mar" },
{"nome": "Ponto" },
{"nome": "Oceano" },
{"nome": "Nereu" },
{"nome": "Proteu" },
{"nome": "Forcis" },
{"nome": "Glauco" },
{"nome": "Tritões" },
{"nome": "Sereias" },
{"nome": "Os Rios" },
{"nome": "Ninfas" },
{"nome": "Os Heróis" },
{"nome": "Teseu" },
{"nome": "Héracles" },
{"nome": "O Escudo de Héracles" },
{"nome": "O Timeu" },
{"nome": "Considerações Finais" }
]},{"nome": "Tema III – Simbologia Teológica em Roma","capitulos": [
{"nome": "Introdução" },
{"nome": "Deuses do Estado" },
{"nome": "Janos" },
{"nome": "Marte" },
{"nome": "Júpiter" },
{"nome": "Juno" },
{"nome": "Vesta" },
{"nome": "Vulcano" },
{"nome": "Saturno" },
{"nome": "Minerva" },
{"nome": "Mercúrio" },
{"nome": "Divindades Agrícolas" },
{"nome": "Fauno" },
{"nome": "Ceres" },
{"nome": "Diana" },
{"nome": "Vertumno" },
{"nome": "Vênus" },
{"nome": "Divindades Infernais" },
{"nome": "Dis Pater" },
{"nome": "Orco" },
{"nome": "Lemures, Larvas" },
{"nome": "Manes" },
{"nome": "Divindades das Águas" },
{"nome": "Diuturna" },
{"nome": "Neptuno" },
{"nome": "Divindades das Cidades" },
{"nome": "Fortuna" },
{"nome": "Gênio" },
{"nome": "Terminus" },
{"nome": "Heróis Divinizados" },
{"nome": "Hércules" },
{"nome": "Rômulo e Remo" },
{"nome": "Enéias" },
{"nome": "Divindades da Família" },
{"nome": "Gênio" },
{"nome": "Os Penates" },
{"nome": "Lar" },
{"nome": "Contribuições Orientais" }
]}]}
