POST  https://nafortaleza.com.br:8443/pedagogia/api/materias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQG5hLmNvbS5iciIsImV4cCI6MTU0OTQ5OTA4NSwiUk9MRVMiOiJST0xFX1VTRVIifQ.2XumgaTZsfzUTodiZ1AMlTp-Ei0X5it5UJUWo-ZFCxnXgUeqIFDqYsuS7JtZW4tDqj47OwulPoX0OLAgjcNUgQ

{"nome": "Simbologia Teológica I","nivel": { "id": 2 },"temas": [
{"nome": "Tema 0 – Prólogo","capitulos": [
{"nome": "Introdução" },
{"nome": "O Valor dos Símbolos na Problemática  Metafísica de Todos os Tempos" },
{"nome": "O Símbolo Como Linguagem do Inefável" },
{"nome": "A Linguagem Entendida como Expessão de uma Idéia" },
{"nome": "Linguagens Ametafísicas e Sub-Linguagens" },
{"nome": "A Linguagem do Instinto, da Vida Quotidiana e da Vida Transcendente" },
{"nome": "O Símbolo Como Conceito" },
{"nome": "Valor dos Hieróglifos" },
{"nome": "Litania de Shu" },
{"nome": "Livro da Oculta Morada" },
{"nome": "Citações Neoplatônicas Sobre o Valor dos Hieróglifos" },
{"nome": "Razão de Ser dos Símbolos" },
{"nome": "Necessidade dos Símbolos para a Explicação do Inexplicado" },
{"nome": "Adendo ao Tema 1 (Introdução) - Perguntas" }
]},{"nome": "Tema I","capitulos": [
{"nome": "Simbologia Teológica no Egito - Introdução" },
{"nome": "Egito e o Seu Zoomorfismo Teológico" },
{"nome": "Análise dos Deuses Egípcios e Outros Elementos Teológicos:" },
{"nome": ".   Divindades Principais" },
{"nome": "Nun" },
{"nome": "Tum ou Atum" },
{"nome": "Ra" },
{"nome": "Amon" },
{"nome": "Hathor" },
{"nome": "Osiris" },
{"nome": "Isis" },
{"nome": "Horus" },
{"nome": "Seth-Tiphon" },
{"nome": "Neftis" },
{"nome": "Thot" },
{"nome": "Anubis" },
{"nome": "Kepher ou Escaravelho" },
{"nome": "Ptah" },
{"nome": "Maat" },
{"nome": "Sekhmet" },
{"nome": "Bastek" },
{"nome": "Nekhebet" },
{"nome": "Khnum" },
{"nome": "Apis" },
{"nome": "Toeris" },
{"nome": "Heket ou Hikit" },
{"nome": "Hapi" },
{"nome": "Bés" },
{"nome": "Ankh" },
{"nome": "Arca de Isis" },
{"nome": "Apap ou Apophis" },
{"nome": "Os Quatro Filhos de Horus" },
{"nome": "Peso do Coraçõs do Morto" },
{"nome": "Esfinge" },
{"nome": "Tarots - Valor dos Hieróglifos:" },
{"nome": "Tarot nº 1" },
{"nome": "Tarot nº 2" },
{"nome": "Tarot nº 3" },
{"nome": "Tarot nº 4" },
{"nome": "Tarot nº 5" },
{"nome": "Tarot nº 6" },
{"nome": "Tarot nº 7" },
{"nome": "Tarot nº 8" },
{"nome": "Tarot nº 9" },
{"nome": "Tarot nº 10" },
{"nome": "Tarot nº 11" },
{"nome": "Tarot nº 12" },
{"nome": "Tarot nº 13" },
{"nome": "Tarot nº 14" },
{"nome": "Tarot nº 15" },
{"nome": "Tarot nº 16" },
{"nome": "Tarot nº 17" },
{"nome": "Tarot nº 18" },
{"nome": "Tarot nº 19" },
{"nome": "Tarot nº 20" },
{"nome": "Tarot nº 21" },
{"nome": "Tarot nº 22" }
]},{"nome": "Tema 2 - Introdução à Simbologia Teológica da África Negra","capitulos": [
{"nome": "Grupo Sul-Oriental" },
{"nome": "Grupo Meridional" },
{"nome": "Grupo Congolês" },
{"nome": "Grupo Nilotico" },
{"nome": "Grupo Sudanês" },
{"nome": "Grupo Voltaico" },
{"nome": "Grupo de Guiné - Grupo Senegambio" },
{"nome": "Vestígios de Antigos Cultos na África Negra" },
{"nome": "Ruínas de Zimbabwé" },
{"nome": "O Grupo X" },
{"nome": ".  Anexo – Outros Símbolos Africanos" }
]}]}
