POST  https://nafortaleza.com.br:8443/pedagogia/api/materias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQG5hLmNvbS5iciIsImV4cCI6MTU0OTQ5OTA4NSwiUk9MRVMiOiJST0xFX1VTRVIifQ.2XumgaTZsfzUTodiZ1AMlTp-Ei0X5it5UJUWo-ZFCxnXgUeqIFDqYsuS7JtZW4tDqj47OwulPoX0OLAgjcNUgQ

{"nome": "Simbologia Teológica Tomo II","nivel": { "id": 2 },"temas": [
{"nome": "Tema I – Introdução","capitulos": [
{"nome": "Introdução" },
{"nome": "Os Quatro Elementos Primordiais" },
{"nome": "Os Quatro Elementos e suas Aplicações" },
{"nome": "Os Deuses e os Elementos" },
{"nome": "Deuses do Fogo" },
{"nome": "Agni" },
{"nome": "Ptah" },
{"nome": "Prometeu" },
{"nome": "Lógica desses Símbolos e suas Representações Divinas" }
]},{"nome": "Tema  II – Simbolismo dos minerais e das pedras preciosas","capitulos": [
{"nome": "FORMAÇÃO DE METAIS E" },
{"nome": "PEDRAS PRECIOSAS" },
{"nome": "LEI DE CORRESPONDÊNCIAS" },
{"nome": "PROPRIEDADES DAS PEDRAS" },
{"nome": "SIGNIFICADO RELIGIOSO DE PEDRAS E METAIS" },
{"nome": "AMULETOS E TALISMÃS" },
{"nome": "Amuletos" },
{"nome": "Fetiches" },
{"nome": "Talismã" },
{"nome": "Pantáculo" },
{"nome": "AS PEDRAS MÁGICAS" },
{"nome": "Gemas" }
]},{"nome": "Tema  III – Simbologia do Reino Vegetal","capitulos": [
{"nome": "A ÁRVORE E AS PLANTAS NA LINGUAGEM SIMBÓLICA" },
{"nome": "BOTÂNICA OCULTA" },
{"nome": "Botanogenia" },
{"nome": "Fisiologia vegetal" },
{"nome": "Fisiognosia vegetal" },
{"nome": "O HOMEM E A PLANTA" },
{"nome": "Das plantas aos homens" },
{"nome": "Alimentação" },
{"nome": "Terapêutica" },
{"nome": "Magia" },
{"nome": "Dos homens às plantas" },
{"nome": "Agricultura mágica" },
{"nome": "Crescimento mágico" },
{"nome": "Palingenesia" },
{"nome": "ESPÍRITOS REGENTES DAS PLANTAS" },
{"nome": "Os Elfos" },
{"nome": "DESCRIÇÃO DE ALGUMAS PLANTAS E" },
{"nome": "SEUS SÍMBOLOS CARACTERÍSTICOS" },
{"nome": "Amusa" },
{"nome": "Acácia" },
{"nome": "Artemísia" },
{"nome": "Camélia" },
{"nome": "Colocasta" },
{"nome": "Azinheira, Zimbo, Fava" },
{"nome": "Girassol, Figueira" },
{"nome": "Loureiro, Lotus" },
{"nome": "Mandrágora, Macieira, Mirto, Mirra" },
{"nome": "Agárico" },
{"nome": "Narciso, Oliveira, Palmeira, Persea" },
{"nome": "Pinheiro, Alecrim, Rosa, Gergelim, Chá, Trevo" }
]},{"nome": "Tema IV - Simbologia do Reino Animal","capitulos": [
{"nome": "CARACTERÍSTICAS GERAIS DO SÍMBOLO" },
{"nome": "SIMBOLISMO GERAL DA AVE" },
{"nome": "Ovo" },
{"nome": "Cisne" },
{"nome": "Ganso" },
{"nome": "Garuda, Águia" },
{"nome": "Cegonha Ibis, Corvo" },
{"nome": "Galo, Fênix" },
{"nome": "Falcão, Pavão Real" },
{"nome": "INSETOS, RÉPTEIS, MAMÍFEROS," },
{"nome": "PEIXES E ANFÍBIOS" },
{"nome": "Abelha" },
{"nome": "Aranha, Asno" },
{"nome": "Boi, Abrutre" },
{"nome": "Cavalo, Cervo, Cinocéfalo" },
{"nome": "Crocodilo, Gato" },
{"nome": "Górgona, Grifo, Javali" },
{"nome": "Leão, Lebre, Lobo, Borboleta" },
{"nome": "Macaco, Peixe Rã" },
{"nome": "Serpente" },
{"nome": "Tigre, Touro" },
{"nome": "ANIMAIS SIMBÓLICOS EM TODOS OS PANTÕES" }
]},{"nome": "Tema V - Simbologia dos Corpos Celestes","capitulos": [
{"nome": "Introdução" },
{"nome": "SIMBOLISMO DOS CORPOS CELESTES" },
{"nome": "ASTROLOGIA" },
{"nome": "O ZODÍACO" },
{"nome": "Antiguidade do zodíaco" },
{"nome": "O grande zodíaco" },
{"nome": "SIGNOS DO ZODÍACO" },
{"nome": "Áries" },
{"nome": "Touro" },
{"nome": "Gêmeos" },
{"nome": "Câncer" },
{"nome": "Leão" },
{"nome": "Virgem" },
{"nome": "Libra" },
{"nome": "Escorpião" },
{"nome": "Sagitário" },
{"nome": "Capricórnio" },
{"nome": "Aquário" },
{"nome": "Peixes" },
{"nome": "OS PLANETAS" },
{"nome": "Lua" },
{"nome": "Mercúrio" },
{"nome": "Vênus" },
{"nome": "Sol" },
{"nome": "Marte" },
{"nome": "Júpiter" },
{"nome": "Saturno" },
{"nome": "Urano" },
{"nome": "Netuno" },
{"nome": "Plutão" },
{"nome": "SINAIS DE CORRESPONDÊNCIA" }
]},{"nome": "Tema VI - Arquitetura Simbólica","capitulos": [
{"nome": "INTRODUÇÃO" },
{"nome": "GENERALIDADES SOBRE ARQUITETURA" },
{"nome": "SIMBÓLICA" },
{"nome": "SIMBOLISMO E ARTE" },
{"nome": "O TEMPLO" },
{"nome": "Megalitos" },
{"nome": "Orientação" },
{"nome": "Carnac" },
{"nome": "Stonehenge" },
{"nome": "Pirâmides" },
{"nome": "Pirâmide de Keops" },
{"nome": "Templo das Inscrições (Palenque)" },
{"nome": "Pirâmide do Adivinho (Uxmal)" },
{"nome": "Pirâmide de Chichen Itzá" },
{"nome": "Pirâmide do Sol (Teotihuacán)" },
{"nome": "RELIGIÃO E ARTE ATRAVÉS DA HISTÓRIA" },
{"nome": "Egito" },
{"nome": "Creta" },
{"nome": "Assíria - Babilônia" },
{"nome": "Índia" },
{"nome": "China" },
{"nome": "Japão" },
{"nome": "Bizâncio" },
{"nome": "Arte árabe ou muçulmana" },
{"nome": "Arte pré-colombiana" },
{"nome": "Grécja" },
{"nome": "Medida áurica" },
{"nome": "Cânone de Polyclates" },
{"nome": "Ordem Dórica" },
{"nome": "Ordem Jônica" },
{"nome": "Ordem Coríntia" },
{"nome": "Idade Média, igrejas e catedrais" },
{"nome": "Características da arte gótica" },
{"nome": "Construção do templo" },
{"nome": "As três tábuas" },
{"nome": "A luz" },
{"nome": "Os astros" }
]},{"nome": "Tema VII - O Homem como Símbolo do \"Infinito","capitulos": [
{"nome": "Epílogo" }
]}]}
