POST  https://nafortaleza.com.br:8443/pedagogia/api/materias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQG5hLmNvbS5iciIsImV4cCI6MTU0OTQ5OTA4NSwiUk9MRVMiOiJST0xFX1VTRVIifQ.2XumgaTZsfzUTodiZ1AMlTp-Ei0X5it5UJUWo-ZFCxnXgUeqIFDqYsuS7JtZW4tDqj47OwulPoX0OLAgjcNUgQ

{"nome": "Religiões Comparadas Área Índica","nivel": { "id": 3 },"temas": [
{"nome": "Tema I RELIGIÓN ÍNDICA: BRAHMANISMO","capitulos": [
{"nome": "LOS VEDAS" },
{"nome": "ESQUEMA GENERAL DE LOS VEDAS" },
{"nome": "CONFORMACIÓN DE UN VEDA" },
{"nome": "DEIDADES DEL PANTEÓN HINDÚ" },
{"nome": "AGNI" },
{"nome": "INDRA" },
{"nome": "SURYA" },
{"nome": "MITRA" },
{"nome": "VARUNA" },
{"nome": "RUDRA" },
{"nome": "TRÍADAS EN EL PANTEÓN HINDÚ" },
{"nome": "BRAHMA" },
{"nome": "VISHNÚ" },
{"nome": "SHIVA" },
{"nome": "CONTRAPARTES FEMENINAS DE LA TRÍADA RELIGIOSA BRAHMÁNICA" },
{"nome": "ESPOSA DE BRAHMA" },
{"nome": "ESPOSA DE VISHNÚ" },
{"nome": "ESPOSA DE SHIVA" },
{"nome": "ADITI" },
{"nome": "USHAS" },
{"nome": "LOS PANIS" },
{"nome": "GANESHA Y KARTIKEYA" },
{"nome": "GANESHA" },
{"nome": "KARTIKEYA" },
{"nome": "VISHVAKARMAN" },
{"nome": "LOS AZVINS" },
{"nome": "ANUMAN" },
{"nome": "LOS NAGAS Y LAS NAGINI" },
{"nome": "LOS RUDRAS" },
{"nome": "LOS MARUTS" },
{"nome": "VASUS" },
{"nome": "LAS ADITYAS" },
{"nome": "YAMA" },
{"nome": "APARICIÓN DE LAS ESCUELAS DE FILOSOFÍA" },
{"nome": "ESCUELA NYAYA DE GOTAMA" },
{"nome": "ESCUELA VAIZECHIKA DE KANADA" },
{"nome": "ESCUELA SANKHYA DE KAPILA" },
{"nome": "ESCUELA YOGA DE PATANJALI" },
{"nome": "ESCUELA PURVA MIMANSA" },
{"nome": "ESCUELA UTTARA MIMANSA" },
{"nome": "COMENTARIO DE SANKARACHARYA" },
{"nome": "OTRO COMENTARIO" }
]},{"nome": "Tema II ÁREA MARGINAL: JAINOS, SIKS, ETC.","capitulos": [
{"nome": "JAINISMO" },
{"nome": "LOS TIRTHAMKARAS" },
{"nome": "RISABHA" },
{"nome": "PARSVA" },
{"nome": "MAHAVIRA" },
{"nome": "SUBDIVISIONES" },
{"nome": "FILOSOFÍA" },
{"nome": "SIKISMO" },
{"nome": "Ceremonia Pahul" },
{"nome": "FRAGMENTOS DE LAS ENSEÑANZAS Y PARÁBOLAS DE NANAK" },
{"nome": "RELIGIÓN TAMIL o TAMUL" }
]},{"nome": "Tema III - BUDHISMO","capitulos": [
{"nome": "VIDA DE BUDHA" },
{"nome": "VERSIÓN EXTRAÍDA DE LOS EVANGELIOS" },
{"nome": "MARCHA DEL BUDHA" },
{"nome": "LA VUELTA DE KANDAKA" },
{"nome": "LA ENTRADA AL LUGAR DE LAS AUSTERIDADES" },
{"nome": "CONSTERNACIÓN GENERAL EN PALACIO" },
{"nome": "EN BÚSQUEDA DEL PRÍNCIPE" },
{"nome": "EL RAJA DE BIMBISARA VISITA AL PRÍNCIPE" },
{"nome": "EL PRÍNCIPE RESPONDE AL RAJA" },
{"nome": "EN EL RETIRO DE ARADA-RAMA" },
{"nome": "LA DERROTA DE MARA" },
{"nome": "LA GRAN REVELACIÓN" },
{"nome": "ALGUNAS ANÉCDOTAS DEL EVANGELIO DE ASVAGOSHA" },
{"nome": "ENTREVISTA CON LOS CINCO BHIKSHUS" },
{"nome": "SE HACE DISCÍPULO EL RAJA DE BIMBISARA" },
{"nome": "EL GRAN DISCÍPULO SE HACE ERMITAÑO" },
{"nome": "PADRE E HIJO" },
{"nome": "EL SEÑOR RECIBE LA DONACIÓN DEL JETAVANA-VIHARA" },
{"nome": "SE LIBRA DEL ELEFANTE ENLOQUECIDO Y DE DEVADATTA" },
{"nome": "LA DAMA AMRA VISITA AL BUDHA" },
{"nome": "EN VIRTUD DE SU PROPIO SER FIJA EL TÉRMINO DE SUS DÍAS" },
{"nome": "LA DIFERENCIA ENTRE LOS LIKHAVIS" },
{"nome": "EL PARANIRVANA" },
{"nome": "EL MAHAPARANIRVANA" },
{"nome": "LALITA-VISTARA" },
{"nome": "FRAGMENTOS DEL EVANGELIO DEL BUDHA, EN BASE AL EVANGELIO CHINO" },
{"nome": "ALEGRÍA" },
{"nome": "SAMSARA Y NIRVANA" },
{"nome": "LA VERDAD REDENTORA" },
{"nome": "NACIMIENTO DEL BUDHA" },
{"nome": "LOS LAZOS DE LA VIDA" },
{"nome": "LOS TRES DOLORES" },
{"nome": "LA RENUNCIA AL MUNDO" },
{"nome": "EL SERMÓN DE BENARES" },
{"nome": "PARÁBOLAS" },
{"nome": "LA CASA INCENDIADA" },
{"nome": "EL CIEGO DE NACIMIENTO" },
{"nome": "EL HIJO PERDIDO" },
{"nome": "LA CRUEL GARZA ENGAÑADA" },
{"nome": "EL BUDHA SEMBRADOR" },
{"nome": "EL PARIA" },
{"nome": "EL PERRO HAMBRIENTO" },
{"nome": "EL DÉSPOTA" },
{"nome": "EL GRANO DE MOSTAZA" },
{"nome": "LAS TRES PERSONALIDADES DEL BUDHA" },
{"nome": "EL FIN DEL SER" },
{"nome": "ALABANZA A TODOS LOS BUDHAS" },
{"nome": "EXPANSIÓN DEL BUDHISMO" },
{"nome": "EXPANSIÓN DEL BUDHISMO EN CHINA" },
{"nome": "ADDENDA" },
{"nome": "TEMAS DE BUDHISMO ESOTÉRICO" },
{"nome": "AMITA BUDHA KWAN-SHAI-YIN Y KWAN-YIN. LO QUE EL LIBRO DE DZYAN Y LAS COMUNIDADES DE LAMAS DICEN ACERCA DE TSONG-KHA-PA" },
{"nome": "PREGUNTAS Y RESPUESTAS" },
{"nome": "ADDENDA SOBRE BUDHISMO ZEN" }
]},{"nome": "Tema IV TIBETANISMO o LAMAÍSMO","capitulos": [
{"nome": "DEIDADES  FEMENINAS" },
{"nome": "YI-DAM" },
{"nome": "EL BARDO TODOL" },
{"nome": "ADDENDA SOBRE RELIGIÓN PRIMITIVA TIBETANA" },
{"nome": "RESEÑA DE LA IMPLANTACIÓN DEL BUDISMO" },
{"nome": "BUDHISMO TIBETANO" },
{"nome": "LAS SECTAS DEL BUDHISMO TIBETANO" },
{"nome": "TEOCRACIA TIBETANA" }
]}]}
